defaults:
  - backend: py-txi
  - launcher: process
  - benchmark: inference 
  - experiment 
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

experiment_name: Yi_4

backend:
  device: cuda
  no_weights: false
  model: "01-ai/Yi-34B"
  device_ids: 0

benchmark:
  input_shapes:
    batch_size: 4
    sequence_length: 512
  new_tokens: 50
  memory: true

# hydra/cli specific settings
hydra:
  run:
    # where to store run results
    dir: runs/Yi/${experiment_name}
  sweep:
    # where to store sweep results
    dir: sweeps/${experiment_name}
  job:
    # change working directory to the run directory
    chdir: true
    env_set:
      OVERRIDE_BENCHMARKS: 1 # ttes
      